In [1]:
import h5py
import numpy as np

In [2]:
data = h5py.File('h5/images2.h5', 'r')
data.keys()

<KeysViewHDF5 ['images', 'target']>

In [3]:
images = data['images'][:]
target = data['target'][:]

In [4]:
images.shape

(12751, 70, 70)

In [5]:
target.shape

(12751, 8)

In [1]:
import numpy as np

In [2]:
a = np.random.randint(0, 10, (2,3,4))
a

array([[[0, 9, 7, 3],
        [1, 0, 0, 5],
        [5, 2, 8, 1]],

       [[9, 6, 2, 1],
        [7, 8, 2, 0],
        [5, 1, 5, 6]]])

In [8]:
a.transpose(2,1,0)

array([[[0, 9],
        [1, 7],
        [5, 5]],

       [[9, 6],
        [0, 8],
        [2, 1]],

       [[7, 2],
        [0, 2],
        [8, 5]],

       [[3, 1],
        [5, 0],
        [1, 6]]])

array([[[0, 9, 7, 3],
        [1, 0, 0, 5],
        [5, 2, 8, 1]],

       [[9, 6, 2, 1],
        [7, 8, 2, 0],
        [5, 1, 5, 6]]])